version: "3.9"

services:
  # Runs DB migrations and exits successfully when done
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: landing-backend:latest
    env_file:
      - ./.env
    entrypoint: ["/app/migrate"]
    restart: "no"

  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: landing-backend:latest
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.backend.rule=Host(`back.tehranbot.me`)"
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=myresolver
      - traefik.http.services.backend.loadbalancer.server.port=8080
    networks:
      - traefik-public
    restart: unless-stopped

networks:
  traefik-public:
    external: true
