// Code generated by ent, DO NOT EDIT.

package ent

import (
	"landing/backend/ent/blog"
	"landing/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescCategory is the schema descriptor for category field.
	blogDescCategory := blogFields[0].Descriptor()
	// blog.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	blog.CategoryValidator = blogDescCategory.Validators[0].(func(string) error)
	// blogDescPath is the schema descriptor for path field.
	blogDescPath := blogFields[2].Descriptor()
	// blog.PathValidator is a validator for the "path" field. It is called by the builders before save.
	blog.PathValidator = blogDescPath.Validators[0].(func(string) error)
}
