basePath: /api
definitions:
  ent.Blog:
    properties:
      category:
        description: Category holds the value of the "category" field.
        type: string
      id:
        description: ID of the ent.
        type: integer
      path:
        description: Path holds the value of the "path" field.
        type: string
      text:
        description: Text holds the value of the "text" field.
        type: string
    type: object
  handlers.CreateBlogRequest:
    properties:
      category:
        type: string
      path:
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
  description: OpenAPI documentation for Landing backend.
  title: Landing Backend API
  version: "1.0"
paths:
  /blogs:
    get:
      parameters:
      - description: Filter by category
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ent.Blog'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: List blogs
      tags:
      - blogs
    post:
      consumes:
      - application/json
      parameters:
      - description: Blog payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateBlogRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ent.Blog'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create a blog post
      tags:
      - blogs
  /blogs/{path}:
    get:
      parameters:
      - description: Blog path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Blog'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get blog by path
      tags:
      - blogs
  /healthz:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - system
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Key
    type: apiKey
swagger: "2.0"
